### ISSUE TITLE
Uncaught Error: Unexpected value 'e' imported by the module 'SharedModule'

### ISSUE THREAD

**Issue by martinsiden** [MurhafSousli/ng2-progressbar#1]
Hello!

I'm trying to implement your version of NProgress in my app, but am currently running into some problems. 

I have a shared module that all other modules import. I added your progressbar like this to it:

`import { NgProgressModule } from 'ng2-progressbar';`

```
@NgModule({
  imports: [
    CommonModule, 
    HttpModule, 
    RouterModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule.forRoot(),
    AccordionModule,
    NgProgressModule
  ],
  declarations: [
  ],
  exports: [
    CommonModule, 
    HttpModule, 
    FormsModule, 
    ReactiveFormsModule,
    TranslateModule,
    AccordionModule,
    NgProgressModule
  ],
  providers: [
      TranslateService
  ]
})
```

But as soon as I do that, I get the following error in the console:
`Uncaught Error: Unexpected value 'e' imported by the module 'SharedModule'`

Am I doing something wrong?

**Comment by MurhafSousli** [comment]
Hi @martinsiden, 
First, don't export modules in exports array, `exports` is only used for components, pipes and directives.
If you are using `NgProgressModule` in  `SharedModule` you just need to add it to your `imports` and that's it.
if the error didn't disappear then there might be something wrong in your current project, try to create a new empty project, and install `NgProgressModule` again, and see if it works

**Comment by martinsiden** [comment]
How come [the official Angular documentation](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#shared-module) exports modules in their "Shared module" example then?

**Comment by MurhafSousli** [comment]
@martinsiden you are right, I never tried exporting modules through modules but some used to export everything else through it (interface, classes..) and it used to cause errors. 
did you try to import the module in a new empty project?

**Comment by MurhafSousli** [comment]
@martinsiden the problem was in gulp.js didn't embed the template correctly, I fixed it and pushed the updates to npm, it should work now
