### ISSUE TITLE
Progress bar gets stuck after one time.

### ISSUE THREAD

**Issue by Vx2gas** [MurhafSousli/ng2-progressbar#10]
Hello,

Pretty cool project here.   However, when I use this project and simple call start(), then done(), then start() again, the progress bar doesn't animate.

After debugging, the `this.trickling$.next();` seems to have lost its subscriber.  
When I make this fix, the problem goes away:

I change the subscribe in **progress.service.ts** constructor to the following:
`.subscribe(() => { });`

Can we get this fixed so I don't have my own copy of the src?

Thanks!

**Comment by MurhafSousli** [comment]
Hi @Vx2gas, To make a fix, you need to fork this repo, apply your fix and then pull a request and I will review it the merge it. :smile: [see creating a pull request guide](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)

Now If you checked the [demo](https://murhafsousli.github.io/ng2-progressbar/) you will see that the prograssbar is working properly, but before I need to see your usage, can you post your code here!

**Comment by letwork** [comment]
Hello,

i have the same behavior as @Vx2gas describes it, in my project.
With the constructor fix it works as expected.

Currently i dont understand why this is not happening in your demo project.

PS: really nice component!

**Comment by MurhafSousli** [comment]
Hi @letwork, I will check this asap
