### ISSUE TITLE
spinner runs invisible in background while there is no progress

### ISSUE THREAD

**Issue by letwork** [MurhafSousli/ng2-progressbar#12]
Hello,

thats not a real problem, but you have constant cpu consumption on 0,5 to 1% on your browser window,
when nothing seems to happen on the website.

If you deactivate the spinner (showSpinner = false), "div class="spinner-icon""  isn't rendered -> no cpu consumption

**Comment by MurhafSousli** [comment]
Hi @letwork thank you for the feedback, I will look into this, there is a couple of tiny changes I will make (no breaking changes), I'm planning to write tests too, can you collaborate?

**Comment by MurhafSousli** [comment]
@letwork I checked it out, I see no performance issue, even 1-2% is totally normal when the tab is active. if you still think there is a performance issue, please demonstrate your tests maybe with screenshots
