### ISSUE TITLE
Progress Bar not disappearing

### ISSUE THREAD

**Issue by dhardtke** [MurhafSousli/ng2-progressbar#14]
Hey,

I am using your progress bar with a custom Http implementation, like this:

```typescript
import {Http, RequestOptions, ConnectionBackend, RequestOptionsArgs, Request, Response} from "@angular/http";
import {NgProgressService} from "ng2-progressbar";
import {Observable} from "rxjs/Observable";

export class CustomHttp extends Http {
    private static pendingRequests: number = 0;

    constructor(_backend: ConnectionBackend, _defaultOptions: RequestOptions, private pService: NgProgressService) {
        super(_backend, _defaultOptions);
    }

    request(url: string|Request, options?: RequestOptionsArgs): Observable<Response> {
        console.log("START: " + (<Request>url).url + " | " + CustomHttp.pendingRequests);

        if (CustomHttp.pendingRequests === 0) {
            this.pService.start();
        }

        CustomHttp.pendingRequests++;

        let req = super.request(url, options).share(); //.publishLast().refCount();

        let requestEnded = () => {
            console.log("DONE: " + (<Request>url).url + " | " + CustomHttp.pendingRequests);
            // on complete
            if (CustomHttp.pendingRequests === 1) {
                // this.pService.done();
                setTimeout(() => {
                    if (CustomHttp.pendingRequests === 0) {
                        console.info("CLOSING");
                        this.pService.done();
                    }
                }, this.pService.trickleSpeed);
            }
            CustomHttp.pendingRequests--;
        };

        req.subscribe(() => {
        }, requestEnded, requestEnded);

        return req;
    }
}
```

Somewhat I can't manage to get the progressbar to disappear properly.
This is the output that I get in the console:
```
06:12:42.091 START: /i18n/en/index.json | 0  app.js:889:9
06:12:42.340 DONE: /i18n/en/index.json | 1  app.js:896:13
06:12:42.852 START: i18n/en/entities.json | 0  app.js:889:9
06:12:42.857 START: /rest/ | 1  app.js:889:9
06:12:43.052 DONE: i18n/en/entities.json | 2  app.js:896:13
06:12:48.100 DONE: /rest/ | 1  app.js:896:13
06:12:48.402 CLOSING
```

Why's that? I am calling .done() on the NgProgressService, but nothing happens.

**Comment by MurhafSousli** [comment]
>                 setTimeout(() => {
>                    if (CustomHttp.pendingRequests === 0) {
>                         console.info("CLOSING");
>                         this.pService.done();
>                     }
>                 }, this.pService.trickleSpeed);

I didn't understand your code! why `setTimeout()` the progressbar! _it won't effect your UI thread._
Use it like this 
```javascript
//before attempting a request
    this.progressService.start();
//after request is done
    this.progress.done();
```

**Comment by dhardtke** [comment]
Did you even consider the possibility that there might be some requests occuring at the same point in time or that take longer than others?

For instance, if request A starts shortly before request B and starts the progress bar, request B takes way longer to load than request A and request A therefore hides the progress bar when request B is still running - the progress bar will be hidden quickly and theres no way to show it until the end of request B.

That's why I used some counters to fix this. But your .done() method does some strange things I am not really understanding.

**Comment by MurhafSousli** [comment]
@dhardtke I have this on my radar, but this need time to investigate for a compatible solution 

This is `done()` method, it only works if the progress has started. 
```javascript
 /** Done */
  done() {
    /** if started complete the progress */
    if (this.isStarted()) {
      this.set(.3 + .5 * Math.random());
      this.set(this.maximum);
    }
  }
```
```javascript
 /** Is progress started*/
  isStarted() {
    return this.progress > 0 && this.progress < this.maximum;
  }
```
Can you help on investigating? the code isn't complicated at all, the logic is all [here](https://github.com/MurhafSousli/ng2-progressbar/blob/master/src/service/progress.service.ts)

**Comment by genuinefafa** [comment]
@dhardtke i'm doing something like this... It might be possible to do some magic using [lengthComputable](https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Monitoring_progress) but it suits my current needs. I'm basing the idea on [http://stackoverflow.com/a/37159100/1098814](this).

What do you think?




`app.module.ts`

```javascript
import { BrowserXhr } from '@angular/http';
import { CustomBrowserXhr } from './_General/CustomBrowserXhr';

@NgModule({
/// ...
  providers: [
/// ...
    { provide: BrowserXhr, useClass: CustomBrowserXhr } ,
/// ...
  ],
/// ...
})
```

`./_General/CustomBrowserXhr.ts`

```javascript
import { Injectable } from '@angular/core';
import { BrowserXhr } from '@angular/http';

import { Observable } from 'rxjs/Observable';

// plugins
import { NgProgressService } from 'ng2-progressbar';


@Injectable()
export class CustomBrowserXhr extends BrowserXhr {
    currentRequest: number = 0;
  constructor(private service:NgProgressService) {
      super();
  }

  build(): any {
    let xhr = super.build();

    xhr.onload = (evt) => {
        this.done()
    }

    xhr.onerror = (evt) =>  {
        this.done()
    }

    xhr.onabort = (evt) =>  {
        this.done()
    }

    xhr.onloadstart = (event) => {
        // console.log(`onloadstart currentRequest= ${this.currentRequest}`, event);
        if (event.lengthComputable) {

        }
        this.currentRequest ++;
        if (!this.service.isStarted())
            this.service.start(); // .progressEventObservable.next(event);
    }

    xhr.onprogress = (event) => {
        // console.log("onprogress", this.currentRequest);
        // console.log("evt onload", event);
        // TODO: use event information to compute pending
    };

    return <any>(xhr);
  }

  done() {
      console.log("done", this.currentRequest);
      this.currentRequest --;
      if (this.currentRequest == 0)
        this.service.done();
  }
}
```

**Comment by MurhafSousli** [comment]
@genuinefafa Looks good, it would be a great solution if we can add an extended version of http to this module so it can be used instead of basic http.

**Comment by genuinefafa** [comment]
@MurhafSousli we might include a `NgProgressCustomBrowserXhr` with exactly this, include in the README.md and make improvements from there. At least as starting point. 

After that, we can _borrow_ code from here https://github.com/chieffancypants/angular-loading-bar/blob/master/src/loading-bar.js#L93 :D

**Comment by MurhafSousli** [comment]
@genuinefafa yes sure 👍

**Comment by genuinefafa** [comment]
you can now check the PR, not sure if it is entirely related with @dhardtke issue doh

**Comment by MurhafSousli** [comment]
Multiple requests is supported in v1.3.0

**Comment by dhardtke** [comment]
Thanks @genuinefafa, your class works perfectly :)

Thanks @MurhafSousli for adapting it so quickly.

**Comment by genuinefafa** [comment]
@dhardtke that's what we do (?)
@MurhafSousli cheers!
