### ISSUE TITLE
npm update always results in update of ng2-progressbar

### ISSUE THREAD

**Issue by dhardtke** [MurhafSousli/ng2-progressbar#18]
Every time I do an `npm update` I get:

    npm update
    client@1.0.0 client\src\main\webapp
    `-- ng2-progressbar@1.3.0

So it seems my npm always updates ng2-progressbar to version 1.3.0, even though it is already installed in the latest version.

**Comment by MurhafSousli** [comment]
Hi @dhardtke I'm not really sure why this happens, I only use `npm install` 😃, If you find the reason let me know

**Comment by dhardtke** [comment]
Why did you close this issue?

Anyway, `npm outdated` gives me this:
```
>npm outdated
Package                            Current         Wanted        Latest  Location
ng2-progressbar                    MISSING          1.3.0         1.3.0  nabla-client
```

**Comment by MurhafSousli** [comment]
This has nothing to do with github tags, It seems that it's only happening on your end, when I run `npm outdated` I don't get it

**Comment by dhardtke** [comment]
Okay, I further investigated this issue.
This is my `package.json`:
```json
{
  "name": "ng2-progressbar-test",
  "private": true,
  "version": "1.0.0",
  "description": "Just a test for Issue #18",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "ng2-progressbar ": "~1.3.0",
    "@angular/common": "^2.0.0",
    "@angular/core": "^2.0.0",
    "@angular/http": "^2.0.0",
    "@angular/platform-browser": "^2.0.0",
    "rxjs": "^5.0.1",
    "zone.js": "^0.7.2"
  },
  "author": "dhardtke",
  "license": "ISC"
}
```

When I run `npm install` I get:
```
ng2-progressbar-issue>npm cache clear
ng2-progressbar-issue>npm install
ng2-progressbar-test@1.0.0 ng2-progressbar-issue
+-- @angular/common@2.4.10
+-- @angular/core@2.4.10
+-- @angular/http@2.4.10
+-- @angular/platform-browser@2.4.10
+-- ng2-progressbar@1.3.0  extraneous
+-- rxjs@5.2.0
| `-- symbol-observable@1.0.4
`-- zone.js@0.7.8
```

Then I run `npm update` and I get:
```
ng2-progressbar-issue>npm update
ng2-progressbar-test@1.0.0 ng2-progressbar-issue
`-- ng2-progressbar@1.3.0
```

This is a minimal example, I am running NodeJS 64 Bit Version 7.6.0 and npm Version 4.3.0.

How come I am the only one where this is happening? Something seems to be wrong, I just can't figure out what it is.

**Comment by MurhafSousli** [comment]
try to change `~1.3.0` to `1.3.0` in your package.json

**Comment by dhardtke** [comment]
Doesn't work, same behavior as before.

**Comment by dhardtke** [comment]
It is still happening with `ngx-progressbar` and Version 2.0.0. Unfortunately I don't really now how the npm registry and package resolution works, but there is clearly something wrong with the configuration of this package :(

**Comment by MurhafSousli** [comment]
@dhardtke No, It is clearly something wrong with your npm usage. why are you using `npm update` ? did I mention this in the documentation? 
You see I have a couple of packages using the exact same configuration and I have never had this issue nor anyone had complained about it.

> Unfortunately I don't really now how the npm registry and package resolution works

Why don't you open this issue on [npm issues](https://github.com/npm/npm/issues)! you will get the right answer and you will learn how it works, and if it turned out that this package has a problem, then you will tell how to fix it and I will be more than happy to do the fix.

but I will not ask them, I will leave this job for you

> but there is clearly something wrong with the configuration of this package :(

You just said that you don't know how it works, how can you judge that the issue is coming from my side?

Personally I update by changing the version manually then `npm install` and problem solved.

**Comment by dhardtke** [comment]
Thanks for your fast reply. First of all, I did not intend to offend you in any way. Your library is great, we use it with great pleasure.

> why are you using `npm update` ? did I mention this in the documentation?

I am using it to update my packages. Usually, the purpose of the package.json's version number set for the dependencies is not to pinpoint the *exact* version required, but to specified a range.

> Why don't you open this issue on npm issues! you will get the right answer and you will learn how it works, and if it turned out that this package has a problem, then you will tell how to fix it and I will be more than happy to do the fix.

Maybe I will create an issue there, but that would be no more than a support request.

What I meant with saying "but there is clearly something wrong with the configuration of this package :(" is that there is a problem probably in the npm registry / published configuration of this package. And I don't know how the npm module resolution and publishing of packages works.

To conclude:
If you do a clean install of ngx-progressbar and then run `npm update` again and again it keeps updating ngx-progressbar from 2.0.0 to 2.0.0.

Even if I specify "2.0.0" in my package.json, it still installs the 2.0.0 again.

And there is something more I wanna say: If you say

> did I mention this in the documentation?

then all I can say about that is: Only cause you don't mention it in your documentation, doesn't mean we shouldn't be using it. `npm update` is a standard command of updating the installed packages to the latest version compatible / considering the version specification in package.json.

I will still try to find out why this is happening and be in touch soon!

**Comment by dhardtke** [comment]
Okay, the publishing process doesn't seem to be that hard:
https://docs.npmjs.com/getting-started/publishing-npm-packages

After further digging I found a space in my local package.json inside _projectDir_/node_modules/ngx-progressbar/package.json:
```json
{
  "_args": [
    [
      {
        "raw": "ngx-progressbar @2.0.0",
        "scope": null,
        "escapedName": "ngx-progressbar ",
        "name": "ngx-progressbar ",
        "rawSpec": "2.0.0",
        "spec": "2.0.0",
        "type": "version"
      },
      "projectDir"
    ]
  ],
  "_from": "ngx-progressbar @2.0.0",
  "_id": "ngx-progressbar@2.0.0",
  "_inCache": true,
  "_location": "/ngx-progressbar",
  "_nodeVersion": "7.7.2",
  "_npmOperationalInternal": {
    "host": "packages-12-west.internal.npmjs.com",
    "tmp": "tmp/ngx-progressbar-2.0.0.tgz_1494016443061_0.5769568374380469"
  },
  "_npmUser": {
    "name": "murhaf",
    "email": "murhafsousli@gmail.com"
  },
  "_npmVersion": "3.10.9",
  "_phantomChildren": {},
  "_requested": {
    "raw": "ngx-progressbar @2.0.0",
    "scope": null,
    "escapedName": "ngx-progressbar ",
    "name": "ngx-progressbar ",
    "rawSpec": "2.0.0",
    "spec": "2.0.0",
    "type": "version"
  },
  "_requiredBy": [
    "#USER"
  ],
  "_resolved": "https://registry.npmjs.org/ngx-progressbar/-/ngx-progressbar-2.0.0.tgz",
  "_shasum": "d3bd331d081458aad3b519b46c8f28046de7e49e",
  "_shrinkwrap": null,
  "_spec": "ngx-progressbar @2.0.0",
  "_where": "projectDir",
  "author": {
    "name": "Murhaf Sousli",
    "email": "murhafsousi@gmail.com"
  },
  "bugs": {
    "url": "https://github.com/MurhafSousli/ngx-progressbar/issues"
  },
  "dependencies": {},
  "description": "A slim customizable progressbar for angular",
  "devDependencies": {},
  "directories": {},
  "dist": {
    "shasum": "d3bd331d081458aad3b519b46c8f28046de7e49e",
    "tarball": "https://registry.npmjs.org/ngx-progressbar/-/ngx-progressbar-2.0.0.tgz"
  },
  "homepage": "https://github.com/MurhafSousli/ngx-progressbar#readme",
  "keywords": [
    "angular",
    "progress",
    "progressbar",
    "loading",
    "xhr",
    "loader",
    "slim",
    "youtube",
    "medium",
    "github"
  ],
  "license": "MIT",
  "main": "bundles/ngx-progressbar.umd.js",
  "maintainers": [
    {
      "name": "murhaf",
      "email": "murhafsousli@gmail.com"
    }
  ],
  "module": "index.js",
  "name": "ngx-progressbar",
  "optionalDependencies": {},
  "peerDependencies": {
    "@angular/common": ">=2.0.0 <2.4.6 || >=2.4.8 <4.0.0-beta.6 || >=4.0.0-beta.8",
    "@angular/core": ">=2.0.0 <2.4.6 || >=2.4.8 <4.0.0-beta.6 || >=4.0.0-beta.8",
    "@angular/http": ">=2.0.0 <2.4.6 || >=2.4.8 <4.0.0-beta.6 || >=4.0.0-beta.8"
  },
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/MurhafSousli/ngx-progressbar.git"
  },
  "scripts": {},
  "typings": "index.d.ts",
  "version": "2.0.0"
}
```

I am sure the space is the issue.

After checking https://registry.npmjs.org/ngx-progressbar I don't really see where the space is coming from.
