### ISSUE TITLE
Add context next to progress bar

### ISSUE THREAD

**Issue by sajeetharan** [MurhafSousli/ng2-progressbar#19]
Is there a way to add context next to spinner ?

Like "Upload is in progress"

**Comment by MurhafSousli** [comment]
Hi @sajeetharan, unfortunately you can't add text elements through this module, but I think you can do that manually, if you start/stop the progress from the same component, then you can do this way

```ts
<ng-progress [toggle]="loading"></ng-progress>
<span *ngIf="loading" style="position: fixed; right: 35px top: 35px;">Upload is in progress</span>
```
adjust the text position and instead of `pService.start()` use `loading=true;`
