### ISSUE TITLE
How to disable the background when ng-progressbar is enabled?

### ISSUE THREAD

**Issue by sajeetharan** [MurhafSousli/ng2-progressbar#21]
how can i make the background inactive when ng-progressbar is enabled?

**Comment by MurhafSousli** [comment]
@sajeetharan what do you mean by make the background inactive, which background?

**Comment by sajeetharan** [comment]
@MurhafSousli  i meant to behave it like a modal window, anyway i found the solution

**Comment by sibabratswain11** [comment]
@MurhafSousli What is the solution? please give the solution.
