### ISSUE TITLE
Property 'progress' is private and only accessible within class 'ProgressComponent'.

### ISSUE THREAD

**Issue by Mage111** [MurhafSousli/ng2-progressbar#24]
Hi,

When upgrade to Angular-4 anf angular\cli 1.0.0 got this error:
`ERROR in C:/GitRepository/src/$$_gendir/node_modules/ng2-progressbar/components/progress/progress.component.ngfactory.ts (1,1): Property 'progress' is private and only accessible within class 'ProgressComponent'.`

Need to change this property to public. AOT (which is enabled via --prod) requires that any property/field/function accessed from within a template be public. This is an Angular restriction. Previously this would only be represented as either a runtime error or unexpected behavior (depending on the usage).

see [#5623](https://github.com/angular/angular-cli/issues/5623)

Thanks.

**Comment by MurhafSousli** [comment]
@Mage111 This is the second time it happens, see #8, maybe we should wait until they fix it!

**Comment by Mage111** [comment]
Sorry, I had a mistake. I was sure that I updated to latest version, but I didn't do it. Now, after updating, all work well.
Thanks for your quickly answer.
