### ISSUE TITLE
Using in progress component twice failed: object unsubscribed

### ISSUE THREAD

**Issue by chagitmalach** [MurhafSousli/ng2-progressbar#25]
Hello,
I using in your ng-progress component, and I have to implement it twice because I have two design for other screens in my application.
But it failed on error : "object unsubscribed " because you are call to unsubscrive in the service when the progress component destroy, and the service is singleton....
How can I implement the progress for two other design?

Thanks,
Chagit.

**Comment by MurhafSousli** [comment]
Hi @chagitmalach, it is not applicable with this module to use 2 instances of ng-progress in one application.
Instead you can bootstrap 2 root component, see [this](http://stackoverflow.com/questions/37066421/angular-2-bootstrap-multi-root-component), and then you can add ng-progress for each one of them.
