### ISSUE TITLE
ERROR in NgProgressModule is not an NgModule

### ISSUE THREAD

**Issue by MateuszG** [MurhafSousli/ng2-progressbar#3]
Hi, cool module but I have a problem.
An error has started to appear after update **angular-cli** from .21 to **1.0.0-beta.24**

>   "dependencies": {
>     "@angular/common": "2.4.1",
>     "@angular/compiler": "2.4.1",
>     "@angular/core": "2.4.1",
>     "@angular/forms": "2.4.1",
>     "@angular/http": "2.4.1",
>     "@angular/material": "^2.0.0-alpha.11-3",
>     "@angular/platform-browser": "2.4.1",
>     "@angular/platform-browser-dynamic": "2.4.1",
>     "@angular/router": "^3.3.1",
>     "angular-cli": "1.0.0-beta.24",
>     "angular2-cookie": "^1.2.6",
>     "core-js": "^2.4.1",
>     "file-saver": "^1.3.3",
>     "flexboxgrid": "^6.3.1",
>     "font-awesome": "^4.7.0",
>     "hammerjs": "^2.0.8",
>     "lodash": "^4.17.2",
>     "muicss": "^0.9.7",
>     "ng2-pagination": "^1.0.1",
>     "ng2-progressbar": "^1.0.3",
>     "ng2-translate": "^5.0.0",
>     "object-fit-images": "^2.5.9",
>     "rxjs": "^5.0.1",
>     "ts-helpers": "^1.1.2",
>     "zone.js": "0.7.4"
>   },
>   "devDependencies": {
>     "@angular/compiler-cli": "2.4.1",
>     "@types/jasmine": "^2.5.38",
>     "@types/lodash": "^4.14.44",
>     "codelyzer": "^2.0.0-beta.3",
>     "jasmine-core": "2.5.2",
>     "jasmine-spec-reporter": "2.7.0",
>     "karma": "1.3.0",
>     "karma-chrome-launcher": "^2.0.0",
>     "karma-cli": "^1.0.1",
>     "karma-jasmine": "^1.1.0",
>     "karma-remap-istanbul": "^0.4.0",
>     "protractor": "4.0.14",
>     "ts-node": "1.7.2",
>     "tslint": "^4.1.1",
>     "typescript": "2.0.10"
>   }
> }

**Comment by MurhafSousli** [comment]
Hi @MateuszG, What is the error?

**Comment by MurhafSousli** [comment]
The package needs to be recompiled, by the time I push the new updates you can use the source typescript in your project

**Comment by MateuszG** [comment]
Now I have:
> ERROR in ./~/ng2-progressbar/dist/index.d.ts
> Module build failed: Error: Debug Failure. False expression: Output generation failed
>     at Object.assert (/media/mateusz/MAGAZYN/PROJECTS/ihar/frontend/node_modules/typescript/lib/typescript.js:2437:23)
>     at Object.transpileModule (/media/mateusz/MAGAZYN/PROJECTS/ihar/frontend/node_modules/typescript/lib/typescript.js:54677:18)
>     at TypeScriptFileRefactor.transpile (/media/mateusz/MAGAZYN/PROJECTS/ihar/frontend/node_modules/@ngtools/webpack/src/refactor.js:165:25)
>     at /media/mateusz/MAGAZYN/PROJECTS/ihar/frontend/node_modules/@ngtools/webpack/src/loader.js:151:37
>  @ ./src/app/app.module.ts 20:0-83
>  @ ./src/main.ts
>  @ multi main

when use import 

> import { NgProgressModule } from '../../node_modules/ng2-progressbar/dist/index.d';

**Comment by MurhafSousli** [comment]
The typescript files doesn't exist on npm, copy the src from [here](https://github.com/MurhafSousli/ng2-progressbar/tree/master/src) into your project e.g. 'temp-folder' and import the module from there like

`import {NgProgressModule} from 'temp-folder'`

**Comment by MurhafSousli** [comment]
@MateuszG The package has been updated to `1.1.1`, problem should be fixed, if you get any issue feel free to reopen
