### ISSUE TITLE
System.config.js

### ISSUE THREAD

**Issue by raff90** [MurhafSousli/ng2-progressbar#4]
great lib mate! anyway would like know on Map and packages for system.config.js since running error Not Found.

GET http://localhost:3000/node_modules/ng2-progressbar  404 (Not Found)

**Comment by MurhafSousli** [comment]
hi @raff90 I don't what you are using but this has to do with your serve task not discovering `node_modules` directory, I suggest you to use webpack starter such as angular-cli or angular-webpack-starter

**Comment by MurhafSousli** [comment]
@raff90 Systemjs is supported now

**Comment by raff90** [comment]
Thanks mate, its worked like charm!
