### ISSUE TITLE
Unmet peer dependencies for newer angular versions

### ISSUE THREAD

**Issue by Phmager** [MurhafSousli/ng2-progressbar#5]
thanks for the progressbar, I get the following error, when I try to use a newer Angular version. You should configure it properly in the package.json.

![image](https://cloud.githubusercontent.com/assets/9350951/21565500/219a0eae-ce99-11e6-9243-b4da05f68d93.png)

**Comment by MurhafSousli** [comment]
Hi @Phmager, don't worry those aren't errors, and they will disappear in the next release

**Comment by MurhafSousli** [comment]
@Phmager I have updated the package to `1.1.1`, please reinstall and if you get an issue feel free to reopen
