### ISSUE TITLE
SystemJS Starter: Error XHR 404 loading (traceur) "ng2-progressbar" 

### ISSUE THREAD

**Issue by jandresampaio** [MurhafSousli/ng2-progressbar#6]
When loading my app, after importing ng2-progressbar, I get the following 

![image](https://cloud.githubusercontent.com/assets/13848625/21774428/651e1e24-d68a-11e6-94a6-72250218dc6d.png)

Systemjs.config file:
![image](https://cloud.githubusercontent.com/assets/13848625/21774489/9c696b72-d68a-11e6-82d7-0f62334e449a.png)

App.module.ts file:
![image](https://cloud.githubusercontent.com/assets/13848625/21774518/b7cd4a14-d68a-11e6-8524-5d1ba6a2e602.png)

![image](https://cloud.githubusercontent.com/assets/13848625/21774560/c7ac74a0-d68a-11e6-9cca-6567ea42a30a.png)

**Comment by jandresampaio** [comment]
Is this working with Angular 2.3.0 ?

**Comment by MurhafSousli** [comment]
Sure, i use it with the latest version, but I don't use `system.js` so I'm not familiar with the error, which starter are you using?

**Comment by jandresampaio** [comment]
@MurhafSousli . Thanks for the update...but I'm not sure what you mean by starter.

**Comment by MurhafSousli** [comment]
@jandresampaio a starter such as [angular-cli](https://github.com/angular/angular-cli) or [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter)..

**Comment by jandresampaio** [comment]
@MurhafSousli 
None of those...we're using Visual Studio with sample ASP.NET core project, using Gulp task runner . Maybe you are refering to angular2-quickstart (as in package.json):

{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },

**Comment by MurhafSousli** [comment]
@jandresampaio I have tried a similar [starter](https://github.com/valor-software/angular2-quickstart), I got the same error, but I couldn't figure out how to fix it.
Umm It seems that the starter is looking for a umd module, which I'm not familiar with.
If you find a solution, please share it here or send me a pull request and I will merge it.

**Comment by alfupe** [comment]
I have seen errors related to traceur when you have multiline comments somewhere at the end or beginning of any component... I'm sorry, my two cents...

**Comment by suryadev-singh** [comment]
Error : ng2-progressbar not found

I am using angularjs2.4.2.
Steps  : 
I have install in node_modules using given command :
define in system.config.js as :
map: {
'ng2-progressbar': 'npm:ng2-progressbar
}
3)- importing in app.module.ts as :
import { NgProgressModule } from "ng2-progressbar";
@NgModule({
imports: [NgProgressModule],
declarations: [ ],
bootstrap: [ ]
})
4)- Importing in app.component.ts as :
import {NgProgressService} from "ng2-progressbar";
@Component({
selector: 'my-app',
template: <ng-progress></ng-progress> <h1>Hello {{name}}</h1>
})
export class AppComponent {
name = 'Angular delhi';
constructor(private pService: NgProgressService) {
}
ngOnInit(){
/** request started /
this.pService.start();
this.http.get('abc.com').subscribe(res){
/* request completed */
this.pService.done();
}
}
}

Then Error in console ------ :

GET http://localhost:3000/node_modules/ng2-progressbar/ 404 (Not Found) zone.js:1645

Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/ng2-progressbar(…) (index):16

**Comment by MurhafSousli** [comment]
Untill we find out what is causing it to fail in system.js, a workaround is to copy the (source typescript)[https://github.com/MurhafSousli/ng2-sharebuttons/tree/master/src] files into your project and import it from there

**Comment by MurhafSousli** [comment]
Related issues for **XHR error (404 Not Found) loading (traceur)** see [#12500](https://github.com/angular/angular/issues/12500), [#11358](https://github.com/angular/angular/issues/11358) on Angular repo

**Comment by MurhafSousli** [comment]
Systemjs is supported now in v1.3.0
