### ISSUE TITLE
Property 'colors' does not exist on type 'NgProgressService'

### ISSUE THREAD

**Issue by saumya04** [MurhafSousli/ng2-progressbar#7]
It seems to me that you've removed multi-colored progress bar from your code.
```
constructor(private progressService: NgProgressService) {
    this.progressService.colors = ['#CE4B45', '#4C8AE6', '#60B25C', '#F0C146'];
}
````

The above `.colors` property is now throwing an error.

> Property 'colors' does not exist on type 'NgProgressService'

By seeing your repo, it seems that you've removed this property.

**Comment by MurhafSousli** [comment]
@saumya04 Yupp I removed because I thought it's not very useful, but you can still do it by binding progressbar `color`

```html
  '<ng-progressbar [color]="color"></ng-progressbar>`
```
then you can easily change the color with a timer that loops over `colors`   

```javascript
    let colors =['green', 'purple', 'red', 'brown', 'cyan'];
    let colorify = true;

    Observable
    .timer(800, 800)
    .take(colors.length)
    .map(index => { 
      this.color = colors[index];
      })
    .repeat()
    .takeWhile(colorify)
    .subscribe();
```
[live plnkr](https://plnkr.co/edit/uhMleiygOQyAUVDrCdsK?p=preview)

**Comment by saumya04** [comment]
@MurhafSousli 
I think this is a breaking change, you should add the above code on the main GitHub Repo page.

**Comment by MurhafSousli** [comment]
@saumya04 This is already mentioned in version 1.1.1, check the [README.MD](https://github.com/MurhafSousli/ng2-progressbar/blob/master/CHANGELOG.md)

**Comment by difagume** [comment]
Hi, how could I get the color effect of the sample page?: [Angular Progressbar](https://murhafsousli.github.io/ngx-progressbar/#/) from the "Test Http Request" button, tnks
