### ISSUE TITLE
1.1.6 AOT failing in ProgressComponent

### ISSUE THREAD

**Issue by Torqode** [MurhafSousli/ng2-progressbar#8]
AOT is failing in the ProgressComponent because 'progress' is injected as a private but is being referenced in the template.

> Error at <path>/compiled/node_modules/ng2-progressbar/components/progress/progress.component.ngfactory.ts:222:93: Property 'progress' is private and only accessible within class 'ProgressComponent'.

**Comment by MurhafSousli** [comment]
@Torqode, `NgProgreesModule` was compiled with AOT and shouldn't fail, please post your code!

**Comment by Torqode** [comment]
Unfortunately I'm not able to post the implementation at the moment, but it doesn't deviate from your example.  I've been able to get it to pass through AOT compiling by doing either one of the following:

1.  Removing the `private` modifier from the progress property in progress.component.ts.
2.  Removing the `[state]="progress.state$ | async"` binding from the progress.component.html.

[SO post about private variables in templates](http://stackoverflow.com/a/39000046/918361)

**Comment by MurhafSousli** [comment]
oh yea you are right about `private`, I didn't get any errors while building!
but what's wrong with the `[state]` ?

**Comment by Torqode** [comment]
Nothing is wrong with the `[state]` per se.  I was using it as a check to make sure the issue was truly with the `private`.  By removing the binding, it removed the only reference to `progress`, so that made AOT happy again.
